---
# handlers file for common
- name: restart ssh
  service: name=ssh state=restarted

- name: restart fail2ban
  service: name=fail2ban state=restarted

- name: reload sysctl
  command: /sbin/sysctl -p

- name: restart ntp
  service: name=ntp state=restarted
