---
# tasks file for mail
- name: update apt cache
  apt: update_cache=yes
  when: ansible_os_family == "Debian"

- name: apt install some useful things
  apt: name={{ item }} state=latest
  with_items:
   - postfix
   - dovecot-imapd
   - sasl2-bin
   - libsasl2-2
   - libsasl2-modules
   - openssl
   - procmail
  when: ansible_os_family == "Debian"

- name: ufw mail rules
  ufw: rule=allow from={{ item }} to_port={{ smtpd_port_1 }}
  with_items:
   - 68.68.97.40
   - 8.23.224.50
   - 8.23.224.110
   - 69.65.5.110
   - 69.65.5.113
   - 69.65.5.119
   - 204.16.252.100
   - 204.16.252.112
  when: ansible_os_family == "Debian"

- name: ufw open mail
  ufw: rule=allow to_port={{ item }}
  with_items: 
   - "{{ smtpd_port_2 }}"
   - "{{ imaps_port }}"
  when: ansible_os_family == "Debian"

- name: add postfix to sasl group
  shell: adduser postfix sasl

- name: add postfix to ssl group
  shell: adduser postfix ssl-cert

- name: add dovecot to ssl group
  shell: adduser dovecot ssl-cert

- name: Create self-signed certificate.
  command: >
    openssl req -new -nodes -x509 -subj "{{ mail_self_signed_cert_subj }}" -days 3650 -keyout {{ mail_ssl_certificate_key }} -out {{ mail_ssl_certificate }} -extensions v3_ca
    creates={{ mail_ssl_certificate }}
    
- name: tempalte etc mailname 
  template: src=mailname.j2 dest=/etc/mailname mode=644 owner=root group=root
  notify: restart postfix

- name: place main cf 
  template: src=main.cf.j2 dest=/etc/postfix/main.cf mode=644 owner=root group=root
  notify: restart postfix

- name: place master cf 
  template: src=master.cf.j2 dest=/etc/postfix/master.cf mode=644 owner=root group=root
  notify: restart postfix

- name: place sasl conf file for postfix
  copy: src=saslsmtpd.conf dest=/etc/postfix/sasl/smtpd.conf mode=644 owner=root group=root
  notify: restart postfix

- name: place sasl conf file for postfix 2
  copy: src=saslsmtpd.conf dest=/etc/postfix/smtpd.conf mode=644 owner=root group=root
  notify: restart postfix

- name: place sasl fwd creds file for postfix
  template: src=sasl_passwd.j2 dest=/etc/postfix/saslsasl_passwd mode=644 owner=root group=root
  notify: restart postfix

- name: place sasl conf file in etc
  copy: src=saslauthd dest=/etc/default/saslauthd mode=644 owner=root group=root
  notify: restart sasl

- name: aliases file
  copy: src=aliases dest=/etc/aliases mode=644 owner=root group=root
  notify: newaliases

- name: place dovecot conf file
  template: src=dovecot.conf.j2 dest=/etc/dovecot/dovecot.conf mode=644 owner=root group=root
  notify: restart dovecot

- name: start sasld 
  service: name=saslauthd state=started enabled=yes

- name: start postfix
  service: name=postfix state=started enabled=yes

- name: start dovecot
  service: name=dovecot state=started enabled=yes

- name: create users
  user: name={{ item.name }} shell=/bin/bash password={{ item.pass }} state=present update_password=always
  with_items: mailusers

- name: place mail dir for users
  file: path=/home/{{ item.name }}/mail recurse=yes state=directory owner={{ item.name }}
  with_items: mailusers

- name: place inbox file for users
  file: path=/home/{{ item.name }}/mail/inbox state=touch owner={{ item.name }}
  with_items: mailusers
