---
- name: temporarily disable SELinux
  selinux: state=disabled

- name: update cache
  yum: name='*' update_cache=yes state=latest

- name: install epel repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present

- name: import epel gpg key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present

- name: upgrade currently installed packages
  yum: name='*' state=latest

- name: install a handful of useful packages
  yum: name={{ item }} state=latest
  with_items:
   - curl
   - fail2ban
   - git
   - irssi
   - lsof
   - net-tools 
   - nmap
   - ntp
   - rsync
   - telnet
   - tmux
   - vim-enhanced
   - wget

- name: remove useless packages
  yum: name={{ item }} state=absent
  with_items:
   - nano
   - popularity-contest
   - accountsservice 
   - libpolkit-gobject-1-0 
   - policykit-1

#- name: remove useless Red Hat packages
#  yum: name={{ item }} state=absent
#  with_items:
#    - blah
#  when: ansible_distribution == "RedHat"

# note: need iptable rules RedHat
